db:
  host: 127.0.0.1
  user: chicken_coop
  pass: supersecret
  db_name: chicken_coop
  dialect: mysql # can be mysql, mariadb, sqlite, postgres or mssql
  storage: # only for sqlite. relative path to db file.
  pool:
    max: 5
    min: 0
    idle: 10000
web:
  host: # leave blank to accept connections on any available IP address
  port: 8000
mqtt:
  host: # leave blank to accept connections on any available IP address
  port: 1883
  stats: true
  id: broker
  publishNewClient: true
  maxInflightMessages: 1024
  client:
    id: coop-duino
    user: chicken_coop
    pass: secret
  backend:
    json: false
    wildcardOne: +
    wildcardSome: '#'
statuses: # Default statuses to populate DB on first run of server. Items can be added or removed from this list as needed.
  door: closed
#  fan: off
  light: off
  water heater: off
beacon:
  interval: 30 # Number of seconds to delay between time beacon messages sent
admin:
  username: admin
  password: secret # Admin password for remote access on frontend.
